@startuml

package a.test.pack.age.one {

	class AClass {
	}

	interface AnInterface {
	}

	class BClass extends AClass {
	}

}

package a.test.pack.age.two {

	class CClass implements AnInterface {
	}

}

package an.other.pack.age {

	class DClass {
	}

}

CClass --> BClass

CClass --> DClass

@enduml